### ISSUE TITLE
Streaming an Apkfile to json results stackoverflow error condition

### ISSUE THREAD

**Issue by droidresearch** [CalebFenton/apkfile#2]
First of all, Thanks for the wonderful project. I have tried to test it and tried it against the sieve.apk file (https://github.com/mwrlabs/drozer/releases/download/2.3.4/sieve.apk)

with the sample code provided in the github example. 
`Writer writer = new OutputStreamWriter(System.out);
gson.toJson(apkFile, writer);`

The code resulted in java.lang.StackoverflowError
Exception in thread "main" java.lang.StackOverflowError
	at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.equals($Gson$Types.java:567)
	at java.util.Arrays.equals(Arrays.java:2829)

I am running the latest build which includes the fix for the above mentioned behavior.
https://github.com/CalebFenton/apkfile/commit/5b6ce0ddc42eb801214c9053cc0d815ef5517b1c

Thanks.

**Comment by CalebFenton** [comment]
Thank you very much for the error report. It should be fixed with: https://github.com/CalebFenton/apkfile/commit/9424e155e218dc9d94de02bcdb8792f8e9acf468

The real problem is I haven't setup any end-to-end tests yet and hardly use the serialization. Thanks  again for pointing this out. Feel free to re-open if this doesn't fix it for you.

**Comment by droidresearch** [comment]
Hi CalebFenton, This is awesome and works like a charm. Thanks for taking time to fix this.
